### ISSUE TITLE
Unexpected behavior for multiline-strings

### ISSUE THREAD

**Issue by MatteoVoges** [omry/omegaconf#1112]
**Describe the bug**
Hey, I'm trying to have a config, where some values are in an escaped interpolation, but in a multiline-string. I think this is a really specific use case, but I think that this applies to all escaped characters.

**To Reproduce**
```python
from omegaconf import OmegaConf as oc, Node

correct = {
    "config": {
        "subconfig": "MULTILINE \n    ${tag:ENV}",
    },
    "values": "${config}",
}

wrong = {
    "values": "${config}",
    "config": {
        "subconfig": "MULTILINE \n    ${tag:ENV}",
    },
}


def escape_tag(input: str, _node_: Node):
    """resolver function, that returns an escaped tag with the input"""
    if "\n" in str(_node_):  # multiline-strings
        escape = "\\\\\\"  # \\\
    else:
        escape = "\\"  # \

    return escape + "${" + input + "}"


oc.register_new_resolver("tag", escape_tag)


cfg_correct = oc.create(correct)
cfg_wrong = oc.create(wrong)

oc.resolve(cfg_correct)
oc.resolve(cfg_wrong)

print(cfg_correct["values"])
# >>> {'values': {'subconfig': 'MULTILINE \n    \\${ENV}'}}
print(cfg_wrong["values"])
# >>> {'values': {'subconfig': 'MULTILINE \n    \\\\\\${ENV}'}

### Another bug ?
print(cfg_correct["values"]["subconfig"])
# >>> [...] ${ENV}
print(cfg_wrong["values"]["subconfig"])
# >>> [...] \${ENV}
```

**Explanation**
Here I have two configs `correct` and `wrong` and the only difference between them is the key order in the python file.
Then I have a custom resolver that produces me an escaped interpolation. In multiline-strings `\` has to be escaped and because of the double escapes (https://github.com/omry/omegaconf/pull/695#discussion_r621335546) we need 3 `\`. Now the diff is that in the `wrong` config, each `\` is escaped again, and it produces 6 `\`.

Another bug (?) is, that when I print the actual strings, that the string gets dumped as multiline and not as quoted, but this could be intended.

**Expected behavior**
I expect, that the order in the config doesn't matter and both configs produce `\${ENV}`.

If there is any kind of workaround like sorting the keys in the config, I would be happy already. 

**Additional context**
- [X] OmegaConf version: latest / master / 2.4.0.dev0
- [X] Python version: 3.10.12
- [X] Operating system: Linux Ubuntu
- [X] Please provide a minimal repro

**Comment by odelalleau** [comment]
Interesting -- I believe this is the same issue as in https://github.com/omry/omegaconf/issues/1081#issuecomment-1570443922 

I'll have a quick look to check if option (2) mentioned in that post would be easy to implement.

**Comment by MatteoVoges** [comment]
There are definitely some similarities. Is there a general problem with producing (escaped) interpolations, because I use them very often.
 But this time I couldn't believe that the key order matters...

**Comment by odelalleau** [comment]
> Is there a general problem with producing (escaped) interpolations

Yes (IMO).

I have a tentative fix in #1113. I can't guarantee if/when a new version will be released with this fix, so you might need to use a custom omegaconf version for now.

Note that this may break some of your existing code if you are relying on the current buggy behavior (for instance I think you'll need to change your `tag` resolver to achieve what you want with this PR).

**Comment by MatteoVoges** [comment]
Thanks for the quick fix. I will try it in a minute. This is just a fix for the escaping, right? Because I still wonder what causes the different behavior regarding the order of the keys in my example. Will it fix that too?

**Comment by odelalleau** [comment]
> I still wonder what causes the different behavior regarding the order of the keys in my example. Will it fix that too?

Yes I expect so.
(just be careful that my first PR was bugged, I just pushed a fixed version)

**Comment by MatteoVoges** [comment]
I don't know if I'm doing something wrong, but if I run your code, my example above is still incorrect. Even if I need to change the `tag` resolver, then the output for both configs should be equal. 
I will try again later today, if I have more time

**Comment by MatteoVoges** [comment]
Hey, I was able to work with the fix a bit and I noticed some breaking changes and some use cases that don't work anymore.
Maybe we could achieve, that this is not the case and we're just fixing the bug in another way.

The bug / breaking change happens when creating an interpolation with a resolver:
```python
from omegaconf import OmegaConf as oc

def produce_interpolation(content: str):
    return "${" + content + "}"

test = {
    "value": "abc",
    "interpolation": "${produce_interpolation:value}",
}

oc.register_new_resolver("produce_interpolation", produce_interpolation)

config = oc.create(test)
print(config)
# >>> {'value': 'abc', 'interpolation': '${produce_interpolation:value}'}

oc.resolve(config)
print(config)
# >>> {'value': 'abc', 'interpolation': '\\${value}'}

oc.resolve(config)
print(config)
# >>> {'value': 'abc', 'interpolation': '\\${value}'}
```

Before the fix, the resolver just produces `${value}` (unescaped) and in the second resolve step it resolves to `abc`. This would also be my favorite behavior for this.

**Comment by odelalleau** [comment]
> Hey, I was able to work with the fix a bit and I noticed some breaking changes and some use cases that don't work anymore.

Yes, this is what I meant in #1113 when I wrote "Note that this is a breaking change".

The current behavior isn't actually intended (there are no tests covering this use case), and can cause issues as we've seen (it's also potentially confusing that a config doesn't behave the same way after it's been resolved).

Can you explain your use case? There may be another way to achieve what you want, for instance maybe you can directly resolve the interpolation you are creating (this is an example that requires direct access to the internal API so it's not great, but it might be possible to expose some of it if needed):
```python
from omegaconf.omegaconf import _node_wrap
from omegaconf._impl import _resolve


def produce_interpolation(content: str, _parent_):
    interpolation = "${" + content + "}"
    return resolve_interpolation(interpolation, parent=_parent_)


def resolve_interpolation(interpolation, parent):
    node = _node_wrap(
        value=interpolation,
        is_optional=False,
        key="__tmp__",
        parent=parent,
    )
    _resolve(node)
    return node._value()
```

We may also consider adding a flag to `resolve()` to indicate whether we want the new or old behavior (but fixing the issue where the resolution order matters). This could actually be useful for `to_yaml()` and `to_container()`, which also require looking at.

**Comment by MatteoVoges** [comment]
I will test your resolver in a minute, thanks for this!

My usecase is large templating of several configs with default values. This is a simplified example of it:
We have a default "class" with a default structure:
```yaml
default:
  valueA: aaa
  valueB: bbb
  api:
    deep:
      nested:
        valueA: ${relative_path:default.valueA}
        valueB: ${relative_path:default.valueB}
```
Then we have special objects that "inherit" from this base class
```yaml
special: ${merge:${default},${special-config}}

special-config:
  valueA: zzz
```

Here we have two resolvers `relative_path`, that converts an absolute interpolation path to a relative one and **important**: delays one resolving stage, and `merge`, that takes several configs and merges them using `OmegaConf.merge()`

If we resolve this in a two step-system the interpolations get resolved after merging and we get the final config:
```yaml
default: [object is resolved, but unimportant]
special-config: [unimportant]

# important
special:
  valueA: zzz
  valueB: bbb
  api:
    deep:
      nested:
        valueA: zzz # overridden value
        valueB: bbb # default value
```
So **TLDR**: We are able to produce reusable objects templated with default values and can have many copies of them where some special values are set. This hierarchy of inheritence can of course go further like a `specialA` and `specialB` object, that get merged with the `special object.`

We at kapitan need this, because many of the values are redundantly defined and we need a simple way to template these efficiently. Then we can search for the key `api` and can copy these config values to helm for example.

I know that this may seem way too complicated and there are certainly 100 methods to do it a lot easier...

**Comment by MatteoVoges** [comment]
Wouldn't be a solution, that the return value of a resolver is always directly the value and there is no escpaping at all?

**Comment by MatteoVoges** [comment]
Your resolver works fine for some cases like the simplified repro from https://github.com/omry/omegaconf/issues/1112#issuecomment-1678573449 but for my most recent use case it isn't suitable because I need the actual resolving happen after the merge.

> We may also consider adding a flag to resolve() to indicate whether we want the new or old behavior (but fixing the issue where the resolution order matters). This could actually be useful for to_yaml() and to_container(), which also require looking at.

I think this would be the best solution, because I might not be the only one, that uses this in their resolvers.

**Comment by odelalleau** [comment]
> Wouldn't be a solution, that the return value of a resolver is always directly the value and there is no escaping at all?

That was the previous behavior. The main issue with it is that `cfg` does not behave the same before / after calling `resolve(cfg)`, which I'd argue is bad in most use cases.

> Some solution that goes in the same direction is the modification of the `_unescape` function in the `grammar_visitor`. This would allow us, to have the behavior with resolvers and interpolations as it was before and we treat escaped interpolations differently. My idea would be to keep escaped interpolations escaped, until we want to have the real value of the config, so accessing, `to_object()` and `to_yaml()`. WDYT?
> 
> UPDATE: I tried with modifying and came up with removing the `+1` in [`grammar_visitor.py` line 359](https://github.com):
> 
> ```diff
> - text = s.text[-(len(s.text) // 2 + 1) :]
> + text = s.text[-(len(s.text) // 2 ) :]
> ```
> 
> and this seems working. I will try to run the tests with it soon...

I'm not sure I entirely follow what you're trying to do here, but this breaks a bunch of tests.

**Comment by MatteoVoges** [comment]
> I'm not sure I entirely follow what you're trying to do here, but this breaks a bunch of tests.

You tried already, or an assumption?

**Comment by odelalleau** [comment]
> > I'm not sure I entirely follow what you're trying to do here, but this breaks a bunch of tests.
> 
> You tried already, or an assumption?

I tried it.

**Comment by MatteoVoges** [comment]
> but in the meantime I updated https://github.com/omry/omegaconf/pull/1113 so that resolve() now takes a flag to control whether or not to escape interpolation strings.

Sounds great. Thank you really much!

> I tried it.

Alright. Then I just got lucky with my testscript...

**Comment by omry** [comment]
Thanks to @MatteoVoges for the report and detailed reproduction, @odelalleau for the investigation and draft PR (#1113), and @Jasha10 for the review.

`OmegaConf.resolve()` is a simple utility that eagerly resolves all interpolations in a config in-place. It works correctly for configs that use only node interpolations (`${key}`) with no custom resolvers. When custom resolvers are involved, results may depend on the depth-first, key insertion order traversal, because custom resolvers can do anything — they may be stateful, have side effects, or return different values on each call.

In the specific case reported here, `values = "${config}"` where `config.subconfig` contains a `${tag:ENV}` resolver interpolation. When `values` is visited first, the traversal follows `values → config → subconfig` and the `tag` resolver fires as a side effect, mutating `config.subconfig` in place. Then when `config` is visited directly in the main loop, the resolver fires again — but this time `_node_` reflects the already-mutated subconfig, not the original string. The resolver's multiline detection logic produces a different result, causing the double-escaping.

**Minimal repro** — same keys, same values, different insertion order, different result:

```python
from omegaconf import OmegaConf

count = 0
def counter(_root_, _node_):
    global count
    count += 1
    return count

OmegaConf.register_new_resolver("counter", counter, use_cache=False)

# b before a: counter fires once, a reuses b's already-resolved value
count = 0
cfg = OmegaConf.create({
    "b": "${counter:}",
    "a": "${b}",
})
OmegaConf.resolve(cfg)
print(cfg)  # {'b': 1, 'a': 1}

# a before b: resolving a forces b's resolver to fire, then b fires again
count = 0
cfg = OmegaConf.create({
    "a": "${b}",
    "b": "${counter:}",
})
OmegaConf.resolve(cfg)
print(cfg)  # {'a': 1, 'b': 2}
```

I considered whether alternative strategies (e.g. collecting all resolved values before applying mutations, or iterating until convergence) could make `resolve()` more robust when custom resolvers are involved. They cannot: because custom resolvers can do anything, no traversal strategy can guarantee consistent results. This is by design.

For configs that use custom resolvers, prefer accessing values lazily (the default OmegaConf behavior) or use `OmegaConf.to_container(cfg, resolve=True)` to get a resolved plain Python container. The limitation is now documented in the docstring and usage docs (see #1286, #1287).
